ZeroBlog.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace ZeroBlog.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

ZeroBlog.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace ZeroBlog.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

ZeroBlog.Web/Models/Layout/UserMenuOrLoginLinkViewModel.cs
using ZeroBlog.Sessions.Dto;

namespace ZeroBlog.Web.Models.Layout
{
    public class UserMenuOrLoginLinkViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

ZeroBlog.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using ZeroBlog.Sessions;
using ZeroBlog.Web.Models.Layout;

namespace ZeroBlog.Web.Controllers
{
    public class LayoutController : ZeroBlogControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ISessionAppService sessionAppService, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }

        [ChildActionOnly]
        public PartialViewResult UserMenuOrLoginLink()
        {
            UserMenuOrLoginLinkViewModel model;

            if (AbpSession.UserId.HasValue)
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                };
            }
            else
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled                    
                };
            }

            return PartialView("_UserMenuOrLoginLink", model);
        }
    }
}

ZeroBlog.Web/Views/Shared/MyLayout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Zero先生</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="~/css/QD_css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/css/QD_css/style.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/QD_js/move-top.js"></script>
    <script type="text/javascript" src="~/Scripts/QD_js/easing.js"></script>
    <script src="~/Scripts/Common/jquery.timers-1.2.js"></script>
    <script type="text/javascript" src="~/Scripts/QD_js/modernizr.custom.js"></script>
    <link href="~/css/QD_css/animate.css" rel="stylesheet" type="text/css" media="all">
    <script src="~/Scripts/QD_js/wow.min.js"></script>


</head>
<body>
    <!--//网页头部-->
    <div class="header" id="home">
        <div class="container">
            <div class="head">
                <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-brand logo wow fadeInLeft animated" data-wow-delay=".5s">
                            <h1><span><a href="~/ZeroBlog_Home/index" style="color:#AF8484;">团<br>子<br>先<br>生<br><span>是<br></span>咸<br>鱼</a></span></h1>
                        </div>

                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        @*<div class="banner">
                                <a class="hvr-rectangle-out wow fadeInDown animated" style="color:yellow" data-wow-delay="1.5s">123</a>
                            </div>*@
                        <ul class="nav navbar-nav wow fadeInDown animated" data-wow-delay="0.5s">
                            <li><a href="~/ZeroBlog_Home/Index"><span class="fontcolor1" data-hover="Home">主页</span></a> </li>
                            <li><a href="#about" class="scroll"><span class="fontcolor1" data-hover="About">心情</span></a></li>
                            <li><a href="#gallery" class="scroll"><span class="fontcolor1" data-hover="Gallery">相册</span></a></li>
                            <li><a href="~/ZeroBlog_Home/single"><span class="fontcolor1" data-hover="Services">博客</span> </a></li>
                            <li><a href="#events" class="scroll"><span class="fontcolor1" data-hover="Events">Demo</span> </a></li>
                            <li><a href="#team" class="scroll"><span class="fontcolor1" data-hover="Team">留言板</span> </a></li>
                            <li><a href="~/ZeroBlog_Home/RegisterUser"><span class="fontcolor1" data-hover="Contact">登录</span></a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->


                </nav>

            </div>
            @*<div class="banner">
                <section class="wrapper wow fadeInUp animated" style="font-size: 13px; " data-wow-delay="0.5s">
                    <h2 style="color: #0065C3; ">ご主人さまおかり、ご饭をする？</h2>
                    <h3 style="color: #ee7070; " class="sentence">
                        お风吕に入る？
                        <div class="popEffect">
                            <span> .そ</span>
                            <span>.れ</span>
                            <span>.と</span>
                            <span>.も</span>
                            <span>.私?</span>
                        </div>
                    </h3>
                </section>
                <a href="~/ZeroBlog_Home/single" class="hvr-rectangle-out wow fadeInDown animated" style="color: #8CBF82; " data-wow-delay=".5s">My Blog</a>

            </div>*@
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    <!--//网页底部-->
    <div class="footer">

        <div class="container">
            <ul class="social">
                <li><a href="#"><i></i></a></li>
                <li><a href="#"><i class="ic1"></i></a></li>
                <li><a href="#"><i class="ic2"></i></a></li>

            </ul>
            <p class="footer-class">Copyright &copy; 2016.Company name All rights reserved.<a target="_blank" href="#">mdj</a></p>

        </div>

    </div>
</body>
</html>

ZeroBlog.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>ZeroBlog</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

<!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

ZeroBlog.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> ZeroBlog</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
                @Html.Action("UserMenuOrLoginLink", "Layout")
            </ul>
        </div>
    </div>
</div>